# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IbanRecognizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IbanRecognizer
  pod 'SwiftGen', '6.6.2'
  
  target 'IbanRecognizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IbanRecognizerUITests' do
    # Pods for testing
  end

end
